export { api, ApiError } from './client';
export { authApi }       from './auth';
export { institutesApi } from './institutes';
export { coursesApi }    from './courses';
export { uploadsApi }    from './uploads';
export { libraryApi }    from './library';
export { generationApi } from './generation';
export { dashboardApi }  from './dashboard';
export { materialsApi }  from './materials';
export type * from './types';
